### ISSUE TITLE
Using latest template symlink with GALAXY_TEST_DB_TEMPLATE

### ISSUE THREAD

**Issue by peterjc** [jmchilton/galaxy-downloads#4]
Hi all,

If I clone the repository, then the symlink `latest.sqlite` seems fine and currently points to `db_gx_rev_0127.sqlite`.

Currently I am using:

```
$ export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
$ ./run_tests.sh -id your_tool_here
```

However, the natural substitute URL using the symlink does not give the SQLite database but just a simple text file containing the filename of the link target. This fails:

```
$ export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/latest.sqlite
$ ./run_tests.sh -id your_tool_here
...
galaxy.model.migrate.check DEBUG 2015-02-27 10:11:18,213 pysqlite>=2 egg successfully loaded for sqlite dialect
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 549, in <module>
    sys.exit( main() )
  File "./scripts/functional_tests.py", line 374, in main
    app = UniverseApplication( **kwargs )
  File "/mnt/galaxy/galaxy-central/lib/galaxy/app.py", line 49, in __init__
    self._configure_models( check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file )
  File "/mnt/galaxy/galaxy-central/lib/galaxy/config.py", line 795, in _configure_models
    create_or_verify_database( db_url, config_file, self.config.database_engine_options, app=self )
  File "/mnt/galaxy/galaxy-central/lib/galaxy/model/migrate/check.py", line 61, in create_or_verify_database
    migrate()
  File "/mnt/galaxy/galaxy-central/lib/galaxy/model/migrate/check.py", line 55, in migrate
    db_schema = schema.ControlledSchema( engine, migrate_repository )
  File "/mnt/galaxy/galaxy-central/eggs/sqlalchemy_migrate-0.7.2-py2.6.egg/migrate/versioning/schema.py", line 32, in __init__
    self.load()
  File "/mnt/galaxy/galaxy-central/eggs/sqlalchemy_migrate-0.7.2-py2.6.egg/migrate/versioning/schema.py", line 44, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/schema.py", line 318, in __new__
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/schema.py", line 381, in _init
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/schema.py", line 408, in _autoload
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 2425, in run_callable
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1968, in run_callable
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 260, in reflecttable
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/reflection.py", line 370, in reflecttable
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/reflection.py", line 223, in get_columns
  File "<string>", line 1, in <lambda>
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/reflection.py", line 47, in cache
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/dialects/sqlite/base.py", line 713, in get_columns
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1449, in execute
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1628, in _execute_text
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1698, in _execute_context
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1691, in _execute_context
  File "/mnt/galaxy/galaxy-central/eggs/SQLAlchemy-0.7.9-py2.6-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 331, in do_execute
migrate.exceptions.DatabaseNotControlledError: (DatabaseError) file is encrypted or is not a database u'PRAGMA table_info("migrate_version")' ()
```

This seems to be a GitHub quirk not dereferencing the symlink. Is there any obvious workaround? The above URL redirects to https://raw.githubusercontent.com/jmchilton/galaxy-downloads/master/latest.sqlite which shows the same behaviour.

**Comment by dannon** [comment]
Yep, we had the same issue and I couldn't figure out an easy way to make github just serve the raw file, following the symlink.  I can try to find where we used it, but I'm pretty sure we just decided to fetch the contents of the symlink in github (so we have the right name) and then download the correct sqlite database from there.

**Comment by dannon** [comment]
Yep, something like:  https://github.com/galaxyproject/planemo/blob/master/planemo/galaxy_config.py#L210

**Comment by peterjc** [comment]
Thanks for the confirmation. So without a similar hack in Galaxy itself, the GitHub hosted symlink won't work with `$GALAXY_TEST_DB_TEMPLATE`. That's a shame, but not a big burden.

I'll stick with periodic updating of the versioned URL, e.g. https://github.com/peterjc/pico_galaxy/commit/412d3fe88b8011f0b690956d129fd72f5b5d4c5c
